package org.example;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for Parser class
 *
 * Verifies Parser correctly identifies valid & invalid
 * program structures based on the specified grammar rules
 *
 * {@code parse()} method returns {@code true} for syntactically correct programs
 *
 * {@code false} for syntax errors
 *
 * @author Avnoor Kaur
 *
 */

class ParserTest {

    /**
     * Tests parsing of syntactically correct program
     *
     * Program contains valid variable declarations, initialization statements,
     * {@code while} loop, {@code calculate} expression, {@code if} conditional block
     *
     * {@link Parser#parse(String)} method should return {@code true}
     */
    @Test
    void testCorrectProgram() {
        String program = """
                var a
                var b
                init a = 1
                init b = 5
                while a != b do
                calculate a = a + 1
                write a
                if a = b then
                write a
                endif
                endwhile
                """;

        Parser parser = new Parser();
        assertTrue(parser.parse(program));
    }

    /**
     * Tests parsing of incorrect program
     *
     * Program includes syntax error in {@code if} statement
     * (missing '=' between {@code a} & {@code b})
     *
     * {@link Parser#parse(String)} should return {@code false}
     * Output should display error message generated by {@code Parser} class
     */
    @Test
    void testIncorrectProgram() {
        String program = """
                var a
                var b
                init a = 5
                init b = 10
                write a
                write b
                if a b then
                write a
                endif
                """;

        Parser parser = new Parser();
        assertFalse(parser.parse(program)); //fails with parse error
    }
}
